"""create core domain tables

Revision ID: f98225df0d46
Revises: 
Create Date: 2026-09-23 11:40:22.674974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98225df0d46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('motto', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('principal_name', sa.String(length=150), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('signature_path', sa.String(length=300), nullable=True),
    sa.Column('stamp_path', sa.String(length=300), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('academic_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_session_school_name')
    )
    op.create_index(op.f('ix_academic_sessions_school_id'), 'academic_sessions', ['school_id'], unique=False)
    op.create_table('assessment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('CA', 'EXAM', name='assessmentcategory', native_enum=False, length=10), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_assessment_type_school_name')
    )
    op.create_index(op.f('ix_assessment_types_school_id'), 'assessment_types', ['school_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_class_school_name')
    )
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('grading_scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remark', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'grade', name='uq_grading_scale_school_grade')
    )
    op.create_index(op.f('ix_grading_scales_school_id'), 'grading_scales', ['school_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_subject_school_name')
    )
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'SCHOOL_ADMIN', 'TEACHER', 'STUDENT', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('class_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'subject_id', name='uq_class_subject')
    )
    op.create_index(op.f('ix_class_subjects_school_class_id'), 'class_subjects', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_class_subjects_subject_id'), 'class_subjects', ['subject_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender', native_enum=False, length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.String(length=150), nullable=True),
    sa.Column('guardian_phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('photo_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='personstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'admission_number', name='uq_student_school_admission_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('profile_photo_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='personstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'employee_id', name='uq_teacher_school_employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('FIRST', 'SECOND', 'THIRD', name='termname', native_enum=False, length=20), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_session_id', 'name', name='uq_term_session_name')
    )
    op.create_index(op.f('ix_terms_academic_session_id'), 'terms', ['academic_session_id'], unique=False)
    op.create_table('report_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('average', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_grade', sa.String(length=5), nullable=True),
    sa.Column('class_position', sa.Integer(), nullable=True),
    sa.Column('number_of_students', sa.Integer(), nullable=True),
    sa.Column('school_days', sa.Integer(), nullable=True),
    sa.Column('days_present', sa.Integer(), nullable=True),
    sa.Column('days_absent', sa.Integer(), nullable=True),
    sa.Column('class_teacher_remark', sa.String(length=300), nullable=True),
    sa.Column('principal_remark', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'PUBLISHED', 'LOCKED', name='resultstatus', native_enum=False, length=20), nullable=False),
    sa.Column('verification_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'term_id', name='uq_report_card_student_term'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_index(op.f('ix_report_cards_student_id'), 'report_cards', ['student_id'], unique=False)
    op.create_index(op.f('ix_report_cards_term_id'), 'report_cards', ['term_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('ca_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('exam_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('subject_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'term_id', name='uq_result_student_subject_term')
    )
    op.create_index(op.f('ix_results_student_id'), 'results', ['student_id'], unique=False)
    op.create_index(op.f('ix_results_subject_id'), 'results', ['subject_id'], unique=False)
    op.create_index(op.f('ix_results_term_id'), 'results', ['term_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'term_id', 'assessment_type_id', name='uq_score_unique_entry')
    )
    op.create_index(op.f('ix_scores_assessment_type_id'), 'scores', ['assessment_type_id'], unique=False)
    op.create_index(op.f('ix_scores_school_class_id'), 'scores', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_scores_student_id'), 'scores', ['student_id'], unique=False)
    op.create_index(op.f('ix_scores_subject_id'), 'scores', ['subject_id'], unique=False)
    op.create_index(op.f('ix_scores_term_id'), 'scores', ['term_id'], unique=False)
    op.create_table('student_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_session_id', name='uq_student_session_enrollment')
    )
    op.create_index(op.f('ix_student_classes_academic_session_id'), 'student_classes', ['academic_session_id'], unique=False)
    op.create_index(op.f('ix_student_classes_school_class_id'), 'student_classes', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_student_classes_student_id'), 'student_classes', ['student_id'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'school_class_id', 'subject_id', name='uq_teacher_class_subject')
    )
    op.create_index(op.f('ix_teacher_assignments_school_class_id'), 'teacher_assignments', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_subject_id'), 'teacher_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_subject_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_school_class_id'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_student_classes_student_id'), table_name='student_classes')
    op.drop_index(op.f('ix_student_classes_school_class_id'), table_name='student_classes')
    op.drop_index(op.f('ix_student_classes_academic_session_id'), table_name='student_classes')
    op.drop_table('student_classes')
    op.drop_index(op.f('ix_scores_term_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_subject_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_student_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_school_class_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_assessment_type_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_results_term_id'), table_name='results')
    op.drop_index(op.f('ix_results_subject_id'), table_name='results')
    op.drop_index(op.f('ix_results_student_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_report_cards_term_id'), table_name='report_cards')
    op.drop_index(op.f('ix_report_cards_student_id'), table_name='report_cards')
    op.drop_table('report_cards')
    op.drop_index(op.f('ix_terms_academic_session_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_class_subjects_subject_id'), table_name='class_subjects')
    op.drop_index(op.f('ix_class_subjects_school_class_id'), table_name='class_subjects')
    op.drop_table('class_subjects')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_grading_scales_school_id'), table_name='grading_scales')
    op.drop_table('grading_scales')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_assessment_types_school_id'), table_name='assessment_types')
    op.drop_table('assessment_types')
    op.drop_index(op.f('ix_academic_sessions_school_id'), table_name='academic_sessions')
    op.drop_table('academic_sessions')
    op.drop_table('schools')
    # ### end Alembic commands ###
